FROM golang:1.25.1-alpine

WORKDIR /home/portfolio

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH

RUN go install github.com/air-verse/air@latest
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0

COPY . .

CMD [ "air" ]

EXPOSE 3306


